colors:
  name: vscode (dark)
  primary:
    background: "#1E1E1E"
    foreground: "#D4D4D4"
  cursor:
    text: "#1d1f21"
    cursor: "#cccccc"
  normal:
    black: "#000000"
    red: "#cd3131"
    green: "#0dbc79"
    yellow: "#e5e510"
    blue: "#2472c8"
    magenta: "#bc3fbc"
    cyan: "#11a8cd"
    white: "#e5e5e5"
  bright:
    black: "#666666"
    red: "#f14c4c"
    green: "#23d18b"
    yellow: "#f5f543"
    blue: "#3b8eea"
    magenta: "#d670d6"
    cyan: "#29b8db"
    white: "#e5e5e5"

cursor:
  style:
    blinking: On
    shape: Block
  unfocused_hollow: true
  vi_mode_style:
    shape: Beam

custom_cursor_colors: true
draw_bold_text_with_bright_colors: true

env:
  # TERM: xterm-256color
  TERM: alacritty

#Available font:
# - UbuntuMono Nerd Font
# - SFMono Nerd Font
# - Monaco Nerd Font
# - FiraCode Nerd Font
# - JetBrainsMono Nerd Font
# - MesloLGL Nerd Font
font:
  normal:
    family: "JetBrainsMono Nerd Font"
    style: Medium
  bold:
    family: "JetBrainsMono Nerd Font"
    style: Bold
  italic:
    family: "JetBrainsMono Nerd Font"
    style: MediumItalic
  bold_italic:
    family: "JetBrainsMono Nerd Font"
    style: BoldItalic
  size: 12.00

key_bindings:
  - { action: SpawnNewInstance, key: Return, mods: Option|Shift }
  - { action: ToggleSimpleFullscreen, key: F, mods: Command|Shift }
  - { action: Copy, key: C, mods: Control|Shift }
  - { action: Paste, key: V, mods: Control|Shift }
  - { chars: "\x11", key: Q, mods: Control }
  - { chars: "\x1b\r", key: Return, mods: Command }
  - { chars: "\x1ba", key: A, mods: Command }
  - { chars: "\x1bb", key: B, mods: Command }
  - { chars: "\x1bd", key: D, mods: Command }
  - { chars: "\x1be", key: E, mods: Command }
  - { chars: "\x1bf", key: F, mods: Command }
  - { chars: "\x1bg", key: G, mods: Command }
  - { chars: "\x1bh", key: H, mods: Command }
  - { chars: "\x1bi", key: I, mods: Command }
  - { chars: "\x1bj", key: J, mods: Command }
  - { chars: "\x1bk", key: K, mods: Command }
  - { chars: "\x1bl", key: L, mods: Command }
  - { chars: "\x1bm", key: M, mods: Command }
  - { chars: "\x1bo", key: O, mods: Command }
  - { chars: "\x1bp", key: P, mods: Command }
  - { chars: "\x1br", key: R, mods: Command }
  - { chars: "\x1bs", key: S, mods: Command }
  - { chars: "\x1bt", key: T, mods: Command }
  - { chars: "\x1bu", key: U, mods: Command }
  - { chars: "\x1bw", key: W, mods: Command }
  - { chars: "\x1bx", key: X, mods: Command }
  - { chars: "\x1by", key: Y, mods: Command }
  - { chars: "\x1bz", key: Z, mods: Command }
  - { chars: "\x1bA", key: A, mods: Command|Shift }
  - { chars: "\x1bB", key: B, mods: Command|Shift }
  - { chars: "\x1bC", key: C, mods: Command|Shift }
  - { chars: "\x1bD", key: D, mods: Command|Shift }
  - { chars: "\x1bE", key: E, mods: Command|Shift }
  - { chars: "\x1bF", key: F, mods: Command|Shift }
  - { chars: "\x1bG", key: G, mods: Command|Shift }
  - { chars: "\x1bH", key: H, mods: Command|Shift }
  - { chars: "\x1bI", key: I, mods: Command|Shift }
  - { chars: "\x1bJ", key: J, mods: Command|Shift }
  - { chars: "\x1bK", key: K, mods: Command|Shift }
  - { chars: "\x1bL", key: L, mods: Command|Shift }
  - { chars: "\x1bM", key: M, mods: Command|Shift }
  - { chars: "\x1bN", key: N, mods: Command|Shift }
  - { chars: "\x1bO", key: O, mods: Command|Shift }
  - { chars: "\x1bP", key: P, mods: Command|Shift }
  - { chars: "\x1bQ", key: Q, mods: Command|Shift }
  - { chars: "\x1bR", key: R, mods: Command|Shift }
  - { chars: "\x1bS", key: S, mods: Command|Shift }
  - { chars: "\x1bT", key: T, mods: Command|Shift }
  - { chars: "\x1bU", key: U, mods: Command|Shift }
  - { chars: "\x1bV", key: V, mods: Command|Shift }
  - { chars: "\x1bW", key: W, mods: Command|Shift }
  - { chars: "\x1bX", key: X, mods: Command|Shift }
  - { chars: "\x1bY", key: Y, mods: Command|Shift }
  - { chars: "\x1bZ", key: Z, mods: Command|Shift }
  - { chars: "\x1b0", key: Key0, mods: Command }
  - { chars: "\x1b1", key: Key1, mods: Command }
  - { chars: "\x1b2", key: Key2, mods: Command }
  - { chars: "\x1b3", key: Key3, mods: Command }
  - { chars: "\x1b4", key: Key4, mods: Command }
  - { chars: "\x1b5", key: Key5, mods: Command }
  - { chars: "\x1b6", key: Key6, mods: Command }
  - { chars: "\x1b7", key: Key7, mods: Command }
  - { chars: "\x1b8", key: Key8, mods: Command }
  - { chars: "\x1b9", key: Key9, mods: Command }

mouse:
  hide_when_typing: true

scrolling:
  history: 10000
  multiplier: 3

selection:
  save_to_clipboard: true
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"

use_thin_strokes: true

window:
  opacity: 0.850
  padding:
    x: 5
    y: 0
  # decorations: buttonless
  # startup_mode: Maximized

working_directory: None
